- name: tap casks
  homebrew_tap:
    tap: caskroom/cask

- name: tap versions
  homebrew_tap:
    tap: '{{ item }}'
  with_items: '{{ homebrew_cask.taps }}'

- name: install casks
  homebrew_cask:
    name: '{{ item }}'
    state: present
    update_homebrew: no
  with_items: '{{ homebrew_cask.apps }}'

- name: clean up space
  command: brew cask cleanup
