- name: turn off analytics
  command: brew analytics off

- name: update
  homebrew: update_homebrew=yes

- name: tap versions
  homebrew_tap:
    tap: '{{ item }}'
  with_items: '{{ dotfiles.homebrew.taps }}'

- name: install packages
  homebrew:
    name: '{{ item }}'
    state: present
  with_items: '{{ dotfiles.homebrew.packages }}'

- name: clean up space
  command: brew cleanup
