- name: use dark menus
  osx_defaults: key=AppleInterfaceStyle value=Dark

- name: disable press-and-hold for keys in favor of key repeat
  osx_defaults: key=ApplePressAndHoldEnabled type=bool value=false

- name: set keyboard initial key repeat rate
  osx_defaults: key=InitialKeyRepeat type=int value=15

- name: set keyboard key repeat rate
  osx_defaults: key=KeyRepeat type=int value=2

- name: enable full keyboard access for all controls
  osx_defaults: key=AppleKeyboardUIMode type=int value=3

- name: disable shadow in screenshots
  osx_defaults: domain=com.apple.screencapture key=disable-shadow type=bool
    value=true

- name: disable auto-correct
  osx_defaults: key=NSAutomaticSpellingCorrectionEnabled type=bool value=true

- name: disable smart quotes and smart dashes
  osx_defaults:
    key: '{{ item }}'
    type: bool
    value: false
  with_items:
    - NSAutomaticDashSubstitutionEnabled
    - NSAutomaticQuoteSubstitutionEnabled

- name: enable a hover effect for stack folders in grid view
  osx_defaults: domain=com.apple.dock key=mouse-over-hilite-stack type=bool
    value=true

- name: set the icon size of dock items to 36 pixels
  osx_defaults: domain=com.apple.dock key=tilesize type=int value=36

- name: change minimize/maximize window effect
  osx_defaults: domain=com.apple.dock key=mineffect value=scale 

- name: minimize windows into their application's icon
  osx_defaults: domain=com.apple.dock key=minimize-to-application type=bool
    value=true

- name: enable spring loading for all dock items
  osx_defaults: domain=com.apple.dock
    key=enable-spring-load-actions-on-all-items type=bool value=true

- name: show indicator lights for open applications in the dock
  osx_defaults: domain=com.apple.dock key=show-process-indicators type=bool
    value=true

- name: automatically hide and show the dock
  osx_defaults: domain=com.apple.dock key=autohide type=bool value=true

- name: make dock icons of hidden applications translucent
  osx_defaults: domain=com.apple.dock key=showhidden type=bool value=true

- name: show status bar
  osx_defaults: domain=com.apple.finder key=ShowStatusBar type=bool value=true

- name: show path bar
  osx_defaults: domain=com.apple.finder key=ShowPathbar type=bool value=true

- name: show icons for hard drives, servers and removable media on the desktop
  osx_defaults:
    domain: com.apple.finder
    key: '{{ item }}'
    type: bool
    value: true
  with_items:
    - ShowExternalHardDrivesOnDesktop
    - ShowHardDrivesOnDesktop
    - ShowMountedServersOnDesktop
    - ShowRemovableMediaOnDesktop

- name: show file extensions
  osx_defaults: key=AppleShowAllExtensions type=bool value=true 

- name: display full path as finder window title
  osx_defaults: domain=com.apple.finder key=_FXShowPosixPathInTitle type=bool
    value=true

- name: search the current folder by default
  osx_defaults: domain=com.apple.finder key=FXDefaultSearchScope value=SCcf 

- name: disable the warning when changing a file extension
  osx_defaults: domain=com.apple.finder key=FXEnableExtensionChangeWarning
    type=bool value=false

- name: use column view in all finder windows by default
  osx_defaults: domain=com.apple.finder key=FXPreferredViewStyle value=Clmv

- name: avoid creation of .DS_Store files on network volumes
  osx_defaults: domain=com.apple.desktopservices key=DSDontWriteNetworkStores
    type=bool value=true

- name: restart affected services and apps
  command: 'killall {{ item }}'
  with_items:
    - Dock
    - Finder
    - SystemUIServer
    - cfprefsd
